spring.application.name=Employee-Managament-System



# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/EmployeeManagement
spring.datasource.username=postgres
spring.datasource.password=@Root2003
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

#ACTUATOR CONFIGURATION
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
info.author=Syed ZUbair

#LOGGING CONFIGURATION
#logging.level.root=info
#logging.pattern.console = %d %c{1.} [%t] --- %m%n